# Generated by Django 2.2.17 on 2021-05-07 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEnquiry',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('phone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Please Enter a valid 10 digit phone number')], verbose_name='Phone Number')),
                ('email_id', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email ID')),
                ('query', models.TextField(verbose_name='Customer Query')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
