# Generated by Django 2.2.17 on 2021-05-07 16:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20210507_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerenquiry',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None, verbose_name='Phone Number'),
        ),
    ]
