# Generated by Django 2.2.17 on 2021-05-07 16:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_auto_20210507_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerenquiry',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number'),
        ),
    ]
