# Generated by Django 2.2.17 on 2021-05-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20210507_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeebBack',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.CustomerEnquiry')),
            ],
        ),
    ]
