# Generated by Django 2.2.17 on 2021-05-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_customerfeebback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerFeebBack',
            new_name='CustomerFeedBack',
        ),
    ]
