# Generated by Django 2.2.17 on 2021-05-08 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_auto_20210508_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
