# Generated by Django 2.2.17 on 2021-05-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0008_customerfeedback_feedback_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='notify_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notification Send Time'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='feedback_notification',
            field=models.BooleanField(default=False, verbose_name='Satisfaction Mail'),
        ),
    ]
