# Generated by Django 2.2.17 on 2021-05-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0009_auto_20210509_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='customer_satisfaction',
            field=models.CharField(choices=[('0', ''), ('1', 'Satisfied'), ('2', 'Unsatisfied')], default=0, max_length=1, verbose_name='Customer Satisfication'),
        ),
    ]
